# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cep_api_development
  username: cep_api
  password: root
  host: localhost
  port: 5433

test:
  <<: *default
  database: cep_api_test
  username: cep_api
  password: root
  host: localhost
  port: 5433

production:
  <<: *default
  database: cep_api_production
  username: cep_api
  password: <%= ENV["CEP_API_DATABASE_PASSWORD"] %>
